services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5432:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql:z